syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.ssd";
option java_outer_classname = "DHTService";

service Comms {
  // Kademlia messages
  rpc ping(Ping) returns (Ping) {}
  rpc store(Store) returns (Store) {}
  rpc findNode(FindNodeRequest) returns (stream FindNodeResponse) {}
  rpc findValue(FindValueRequest) returns (stream FindValueResponse) {}

  // send message
  rpc broadcastMessage(Message) returns (Empty) {} // todo
  rpc sendMessage(Message) returns (Empty) {} // todo
  // etc
}

message Empty {
}

message Ping {
  bytes nodeId = 1;
  int32 reqNodePort = 2;
}

message Store {
  bytes reqNodeId = 1;
  int32 reqNodePort = 2;
  bytes nodeId = 3; //add to Contact message?
  bytes key = 4; //add to Contact message?
  bytes value = 5; //add to Contact message?
}

message FindNodeRequest {
  bytes reqNodeId = 1;
  int32 reqNodePort = 2;
  bytes nodeId = 3;
}

message FindNodeResponse {
  bytes nodeId = 1;
  string address = 2;
  int32 nodePort = 3;
  uint64 lastSeenTime = 4;
}

message FindValueRequest {
  // todo
}

message FindValueResponse {
  // todo
}

message Message {
  bytes senderID = 1;
  int32 senderPort = 2;
  bytes message = 3;
}