syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.ssd";
option java_outer_classname = "DHTService";

service P2PGrpcService {
  rpc ping(ProtoNodeContact) returns (ProtoNodeContact) {}
  rpc store(ProtoContent) returns (ProtoContent){}
  rpc findNode(ProtoTargetContact) returns (ProtoFindNodeResponse){}
  rpc findValue(ProtoTargetContact) returns (ProtoFindValueResponse){}
  rpc sendMessage(ProtoMessage) returns (ProtoMessageResponse) {}
  rpc broadcastMessage(ProtoBroadcastMessage) returns (ProtoNodeContact) {}
}

message ProtoNodeContact {
  string nodeIpAddress = 1;
  uint32 nodePort = 2;
  bytes nodeId = 3;
}

message ProtoContent {
  ProtoNodeContact sendingNode = 1;
  bytes originalPublisherId = 2;
  bytes key = 3;
  bytes value = 4;
}

message ProtoNodeContactList {
  repeated ProtoNodeContact nodes = 1;
}

message ProtoTargetContact {
  ProtoNodeContact sendingNode = 1;
  bytes target = 2;
}

message ProtoFindNodeResponse {
  ProtoNodeContact sendingNode = 1;
  ProtoNodeContactList foundNodes = 2;
}

enum DataType {
  FOUND_VALUE = 0;
  FOUND_NODES = 1;
}

message ProtoFindValueResponse {
  ProtoNodeContact sendingNode = 1;
  DataType dataType = 2;
  ProtoContent foundValue = 3;
  ProtoNodeContactList foundNodes = 4;
}

message ProtoMessage {
  ProtoNodeContact sendingNode = 1;
  bytes message = 2;
}

message ProtoMessageResponse {
  ProtoNodeContact sendingNode = 1;
  bytes messageResponse = 2;
}

message ProtoBroadcastMessage {
  ProtoNodeContact sendingNode = 1;
  int32 depth = 2;
  bytes messageId = 3;
  bytes message = 4;
}
